FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

# MODIFICATION ICI : On force uv à utiliser le Python 3.11 du système
RUN uv sync --frozen --python /usr/local/bin/python

COPY . .

ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT ["dbt"]